# Commonly used to bundle an application's files before deployment,
# creating an artifact that can be used in subsequent steps
# or uploaded to a deployment target or in the cloud storage (ex. Azure Blob storage).
name: App build (generate artifact)

on:
  push:
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Test Suite
        run: npm run test

      - name: Package Next.js App
        # The vertical bar (|) is a YAML "literal block scalar" that allows you to write multi-line commands.
        # It preserves line breaks in the commands that follow.
        # -r flag tells the zip command to work recursively, so it includes all subdirectories and their contents.
        # -x flag excludes unnecessary files
        run: |
          zip -r nextjs-package.zip -x "node_modules/*" ".git/*" ".idea/*"

      # Upload Actions Artifacts from your workflow run details in GitHub UI.
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-package-app-artifact
          path: nextjs-package.zip