# Commonly used to bundle an application's files before deployment,
# creating an artifact that can be used in subsequent steps
# or uploaded to a deployment target or in the cloud storage (ex. Azure Blob storage).
name: App build (generate artifact)

on:
  push:
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Version
        id: package-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: npm install

      - name: Run Test Suite
        run: npm run test

      - name: Package Next.js App
        # The vertical bar (|) is a YAML "literal block scalar" that allows you to write multi-line commands.
        # It preserves line breaks in the commands that follow.
        # zip -> Use the zip utility
        # -r -> Recursively include subdirectories all subdirectories and their contents
        # nextjs-package-v${{ steps.package-version.outputs.version }}.zip -> Name of the output zip file with id
        # . -> Include all files from the current directory (this was missing in your command)
        # -x -> Exclude excludes unnecessary files by patterns
        run: |
          zip -r nextjs-package-v${{ steps.package-version.outputs.version }}.zip . -x "node_modules/*" ".git/*" ".idea/*"

      # Upload Actions Artifacts from your workflow run details in GitHub UI.
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-package-v${{ steps.package-version.outputs.version }}
          path: nextjs-package-v${{ steps.package-version.outputs.version }}.zip